// Each segment is either a clickable word (has reading/meaning)
// or a particle/punctuation (reading and meaning are null)
export const ARTICLE = {
  title: '日本の再生可能エネルギーが新記録を達成',
  subtitle: '環境 · 読み時間 約4分',
  segments: [
    { text: '日本', reading: 'にほん', meaning: 'Japan', jlpt: 'N5' },
    { text: 'の', reading: null, meaning: null },
    { text: '再生可能', reading: 'さいせいかのう', meaning: 'renewable', jlpt: 'N1' },
    { text: 'エネルギー', reading: 'エネルギー', meaning: 'energy', jlpt: 'N2' },
    { text: 'が', reading: null, meaning: null },
    { text: '新', reading: 'あたらしい', meaning: 'new', jlpt: 'N5' },
    { text: '記録', reading: 'きろく', meaning: 'record', jlpt: 'N3' },
    { text: 'を', reading: null, meaning: null },
    { text: '達成', reading: 'たっせい', meaning: 'to achieve', jlpt: 'N2' },
    { text: 'しました', reading: null, meaning: null },
    { text: '。\n\n', reading: null, meaning: null },

    { text: '先週', reading: 'せんしゅう', meaning: 'last week', jlpt: 'N4' },
    { text: '、', reading: null, meaning: null },
    { text: '国内', reading: 'こくない', meaning: 'domestic', jlpt: 'N2' },
    { text: 'の', reading: null, meaning: null },
    { text: '太陽光', reading: 'たいようこう', meaning: 'solar light', jlpt: 'N1' },
    { text: '発電', reading: 'はつでん', meaning: 'power generation', jlpt: 'N2' },
    { text: 'が', reading: null, meaning: null },
    { text: '過去', reading: 'かこ', meaning: 'the past', jlpt: 'N3' },
    { text: '最高', reading: 'さいこう', meaning: 'highest / maximum', jlpt: 'N3' },
    { text: 'の', reading: null, meaning: null },
    { text: '出力', reading: 'しゅつりょく', meaning: 'output', jlpt: 'N2' },
    { text: 'を', reading: null, meaning: null },
    { text: '記録', reading: 'きろく', meaning: 'record', jlpt: 'N3' },
    { text: 'し', reading: null, meaning: null },
    { text: '、', reading: null, meaning: null },
    { text: '全国', reading: 'ぜんこく', meaning: 'nationwide', jlpt: 'N3' },
    { text: 'の', reading: null, meaning: null },
    { text: '電力', reading: 'でんりょく', meaning: 'electric power', jlpt: 'N2' },
    { text: '需要', reading: 'じゅよう', meaning: 'demand', jlpt: 'N2' },
    { text: 'の', reading: null, meaning: null },
    { text: '約', reading: 'やく', meaning: 'approximately', jlpt: 'N3' },
    { text: '40％', reading: null, meaning: null },
    { text: 'を', reading: null, meaning: null },
    { text: '賄い', reading: 'まかない', meaning: 'to cover / to provide', jlpt: 'N1' },
    { text: 'ました', reading: null, meaning: null },
    { text: '。\n\n', reading: null, meaning: null },

    { text: '政府', reading: 'せいふ', meaning: 'government', jlpt: 'N3' },
    { text: 'は', reading: null, meaning: null },
    { text: '2030年', reading: null, meaning: null },
    { text: 'までに', reading: null, meaning: null },
    { text: '再生可能', reading: 'さいせいかのう', meaning: 'renewable', jlpt: 'N1' },
    { text: 'エネルギー', reading: 'エネルギー', meaning: 'energy', jlpt: 'N2' },
    { text: 'の', reading: null, meaning: null },
    { text: '割合', reading: 'わりあい', meaning: 'proportion / ratio', jlpt: 'N2' },
    { text: 'を', reading: null, meaning: null },
    { text: '60％', reading: null, meaning: null },
    { text: '以上', reading: 'いじょう', meaning: 'or more / above', jlpt: 'N4' },
    { text: 'に', reading: null, meaning: null },
    { text: '引き上げる', reading: 'ひきあげる', meaning: 'to raise / to increase', jlpt: 'N1' },
    { text: '目標', reading: 'もくひょう', meaning: 'goal / target', jlpt: 'N3' },
    { text: 'を', reading: null, meaning: null },
    { text: '掲げており', reading: 'かかげており', meaning: 'to set forth / to hold up a goal', jlpt: 'N1' },
    { text: '、', reading: null, meaning: null },
    { text: '今回', reading: 'こんかい', meaning: 'this time / now', jlpt: 'N3' },
    { text: 'の', reading: null, meaning: null },
    { text: '成果', reading: 'せいか', meaning: 'result / achievement', jlpt: 'N2' },
    { text: 'は', reading: null, meaning: null },
    { text: 'その', reading: null, meaning: null },
    { text: '大きな', reading: 'おおきな', meaning: 'big / great', jlpt: 'N5' },
    { text: '一歩', reading: 'いっぽ', meaning: 'one step', jlpt: 'N3' },
    { text: 'となりました', reading: null, meaning: null },
    { text: '。', reading: null, meaning: null },
  ]
}
